import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import authRoutes from './routes/auth.routes.js';
import catalogRoutes from './routes/catalog.routes.js';
import resourceRoutes from './routes/resource.routes.js';
import userRoutes from './routes/user.routes.js';
import adminRoutes from './routes/admin.routes.js';
import aiRoutes from './routes/ai.routes.js';
import { errorHandler, notFound } from './middlewares/errors.js';

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173' }));
app.use(express.json({ limit: '1mb' }));
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 500 }));
app.get('/api/health', (req, res) => res.json({ status: 'ok', service: 'Digital Learning Resources API' }));
app.use('/api/auth', authRoutes);
app.use('/api', catalogRoutes);
app.use('/api/resources', resourceRoutes);
app.use('/api', userRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/ai', aiRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
