import { Router } from 'express';
import { Approval, ActivityLog, Category, DownloadHistory, LearningResource, ResourceFile, Role, Subject, User } from '../models/index.js';
import { authenticate, authorize } from '../middlewares/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { logActivity } from '../utils/activity.js';

const router = Router();
router.use(authenticate, authorize('ADMIN'));
router.get('/users', asyncHandler(async (req, res) => res.json({ items: await User.findAll({ attributes: { exclude: ['passwordHash'] }, include: Role, order: [['createdAt', 'DESC']] }) })));
router.put('/users/:id/status', asyncHandler(async (req, res) => { if(Number(req.params.id)===req.user.id)return res.status(400).json({message:'Không thể tự khóa tài khoản của chính mình.'}); if(!['ACTIVE','LOCKED'].includes(req.body.status))return res.status(400).json({message:'Trạng thái không hợp lệ.'}); const user = await User.findByPk(req.params.id); if (!user) return res.status(404).json({ message: 'Không tìm thấy người dùng.' }); await user.update({ status: req.body.status }); await logActivity(req.user.id,'USER_STATUS',`User #${user.id}: ${user.status}`); res.json({ message: 'Đã cập nhật trạng thái.', user: { id: user.id, fullName: user.fullName, email: user.email, status: user.status, roleId: user.roleId } }); }));
router.put('/users/:id/role', asyncHandler(async (req, res) => { if(Number(req.params.id)===req.user.id)return res.status(400).json({message:'Không thể tự thay đổi vai trò của chính mình.'}); if(!['STUDENT','LECTURER'].includes(req.body.role))return res.status(400).json({message:'Vai trò không hợp lệ.'}); const user = await User.findByPk(req.params.id), role = await Role.findOne({ where: { name: req.body.role } }); if (!user || !role) return res.status(404).json({ message: 'Người dùng hoặc vai trò không tồn tại.' }); await user.update({ roleId: role.id }); await logActivity(req.user.id,'USER_ROLE',`User #${user.id}: ${req.body.role}`); res.json({ message: 'Đã cập nhật vai trò.' }); }));
router.get('/approvals', asyncHandler(async (req, res) => res.json({ items: await LearningResource.findAll({ where: { status: 'PENDING' }, include: [{ model: User, as: 'uploader', attributes: ['id', 'fullName'] }, Subject, Category, { model: ResourceFile, as: 'file', attributes: ['id', 'originalName', 'mimeType', 'extension', 'size', 'resourceId'] }], order: [['createdAt', 'ASC']] }) })));
router.put('/approvals/:id/approve', asyncHandler(async (req, res) => { const item = await LearningResource.findByPk(req.params.id); if (!item) return res.status(404).json({ message: 'Không tìm thấy học liệu.' }); if(item.status!=='PENDING')return res.status(409).json({message:'Chỉ có thể duyệt học liệu đang chờ duyệt.'}); await item.update({ status: 'APPROVED', rejectionReason: null }); await Approval.create({ resourceId: item.id, adminId: req.user.id, action: 'APPROVED' }); await logActivity(req.user.id,'RESOURCE_APPROVE',`Học liệu #${item.id}: ${item.title}`); res.json({ message: 'Đã duyệt học liệu.', item }); }));
router.put('/approvals/:id/reject', asyncHandler(async (req, res) => { if (!req.body.reason?.trim()) return res.status(400).json({ message: 'Phải nhập lý do từ chối.' }); const item = await LearningResource.findByPk(req.params.id); if (!item) return res.status(404).json({ message: 'Không tìm thấy học liệu.' }); if(item.status!=='PENDING')return res.status(409).json({message:'Chỉ có thể từ chối học liệu đang chờ duyệt.'}); await item.update({ status: 'REJECTED', rejectionReason: req.body.reason.trim() }); await Approval.create({ resourceId: item.id, adminId: req.user.id, action: 'REJECTED', reason: req.body.reason.trim() }); await logActivity(req.user.id,'RESOURCE_REJECT',`Học liệu #${item.id}: ${item.title}`); res.json({ message: 'Đã từ chối học liệu.', item }); }));
router.get('/statistics', asyncHandler(async (req, res) => res.json({ users: await User.count(), resources: await LearningResource.count(), pending: await LearningResource.count({ where: { status: 'PENDING' } }), approved:await LearningResource.count({where:{status:'APPROVED'}}), rejected:await LearningResource.count({where:{status:'REJECTED'}}), downloads: await DownloadHistory.count(), topResources:await LearningResource.findAll({where:{status:'APPROVED'},attributes:['id','title','downloadCount'],order:[['downloadCount','DESC']],limit:5}) })));
router.get('/activities', asyncHandler(async (req,res)=>res.json({items:await ActivityLog.findAll({include:[{model:User,attributes:['id','fullName']}],order:[['createdAt','DESC']],limit:20})})));
export default router;
