import { useEffect,useMemo,useState } from 'react';import { api } from '../api/client.js';import Icon from '../components/Icon.jsx';import { useToast } from '../contexts/ToastContext.jsx';
const roleLabel={STUDENT:'Sinh viên',LECTURER:'Giảng viên',ADMIN:'Quản trị viên'};
export default function Admin(){const [stats,setStats]=useState({}),[pending,setPending]=useState([]),[users,setUsers]=useState([]),[activities,setActivities]=useState([]),[subjects,setSubjects]=useState([]),[categories,setCategories]=useState([]),[rejectItem,setRejectItem]=useState(null),[reason,setReason]=useState(''),[query,setQuery]=useState(''),[roleFilter,setRoleFilter]=useState(''),[catalogModal,setCatalogModal]=useState(null),{notify}=useToast();
  const load=async()=>{const requests=[api.get('/admin/statistics'),api.get('/admin/approvals'),api.get('/admin/users'),api.get('/admin/activities'),api.get('/subjects'),api.get('/categories')];const [s,p,u,a,sub,cat]=await Promise.allSettled(requests);if(s.status==='fulfilled')setStats(s.value.data);if(p.status==='fulfilled')setPending(p.value.data.items);if(u.status==='fulfilled')setUsers(u.value.data.items);if(a.status==='fulfilled')setActivities(a.value.data.items);if(sub.status==='fulfilled')setSubjects(sub.value.data.items);if(cat.status==='fulfilled')setCategories(cat.value.data.items);const failed=[s,p,u,a,sub,cat].filter(x=>x.status==='rejected');if(failed.length)notify(`${failed.length} mục dữ liệu chưa tải được. Hãy thử lại.`,'error')};useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>users.filter(x=>(!roleFilter||x.Role?.name===roleFilter)&&(`${x.fullName} ${x.email}`.toLowerCase().includes(query.toLowerCase()))),[users,query,roleFilter]);
  const approve=async id=>{try{await api.put(`/admin/approvals/${id}/approve`);notify('Đã duyệt học liệu.');load()}catch(e){notify(e.message,'error')}};const reject=async()=>{if(!reason.trim())return;try{await api.put(`/admin/approvals/${rejectItem.id}/reject`,{reason});notify('Đã từ chối học liệu.');setRejectItem(null);setReason('');load()}catch(e){notify(e.message,'error')}};
  const userAction=async(user,type,value)=>{if(!confirm(`Xác nhận cập nhật tài khoản ${user.fullName}?`))return;try{await api.put(`/admin/users/${user.id}/${type}`,type==='role'?{role:value}:{status:value});notify('Đã cập nhật người dùng.');load()}catch(e){notify(e.message,'error')}};
  const saveCatalog=async()=>{const {kind,item,name}=catalogModal,path=kind==='subject'?'subjects':'categories';if(!name?.trim())return;try{item?await api.put(`/${path}/${item.id}`,{name}):await api.post(`/${path}`,{name});notify('Đã lưu dữ liệu.');setCatalogModal(null);load()}catch(e){notify(e.message,'error')}};
  const deleteCatalog=async(kind,item)=>{if(!confirm(`Xóa “${item.name}”?`))return;try{await api.delete(`/${kind==='subject'?'subjects':'categories'}/${item.id}`);notify('Đã xóa dữ liệu.');load()}catch(e){notify(e.message,'error')}};
  const cards=[['Người dùng',stats.users,'users','blue'],['Tổng học liệu',stats.resources,'book','violet'],['Chờ duyệt',stats.pending,'file','amber'],['Lượt tải',stats.downloads,'download','green']];return <div className="container page-space"><div className="page-header"><div><span className="eyebrow">Trung tâm điều hành</span><h1>Dashboard quản trị</h1><p>Theo dõi và kiểm soát hoạt động của toàn bộ hệ thống.</p></div><span className="header-icon"><Icon name="shield" size={28}/></span></div><div className="row g-3 stat-grid">{cards.map(([label,value,icon,tone])=><div className="col-6 col-xl-3" key={label}><div className={`stat-card ${tone}`}><span><Icon name={icon} size={24}/></span><div><strong>{value??0}</strong><small>{label}</small></div></div></div>)}</div>
  <section className="surface-card admin-section"><div className="section-title-row"><div><span className="eyebrow">Kiểm duyệt nội dung</span><h2>Học liệu chờ duyệt</h2></div><span className="count-badge">{pending.length}</span></div>{pending.length?<div className="table-responsive"><table className="table modern-table align-middle"><thead><tr><th>Tài liệu</th><th>Người đăng</th><th>Môn học</th><th>Thao tác</th></tr></thead><tbody>{pending.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.file?.originalName}</small></td><td>{x.uploader?.fullName}</td><td>{x.Subject?.name}</td><td><div className="table-actions"><button className="btn btn-success btn-sm" onClick={()=>approve(x.id)}>Duyệt</button><button className="btn btn-outline-danger btn-sm" onClick={()=>setRejectItem(x)}>Từ chối</button></div></td></tr>)}</tbody></table></div>:<div className="mini-empty"><Icon name="shield" size={34}/><h3>Đã xử lý tất cả</h3><p>Hiện không có tài liệu đang chờ duyệt.</p></div>}</section>
  <section className="surface-card admin-section"><div className="section-title-row"><div><span className="eyebrow">Cộng đồng</span><h2>Quản lý người dùng</h2></div><span className="count-badge">{filtered.length}</span></div><div className="admin-filters"><input className="form-control" placeholder="Tìm theo tên hoặc email" value={query} onChange={e=>setQuery(e.target.value)}/><select className="form-select" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">Mọi vai trò</option><option value="STUDENT">Sinh viên</option><option value="LECTURER">Giảng viên</option><option value="ADMIN">Quản trị viên</option></select></div><div className="table-responsive"><table className="table modern-table align-middle"><thead><tr><th>Người dùng</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><div className="person-cell"><span>{x.fullName.charAt(0).toUpperCase()}</span><strong>{x.fullName}</strong></div></td><td>{x.email}</td><td><span className="role-badge">{roleLabel[x.Role?.name]}</span></td><td><span className={`status-pill ${x.status==='ACTIVE'?'status-APPROVED':'status-REJECTED'}`}><i/>{x.status==='ACTIVE'?'Hoạt động':'Đã khóa'}</span></td><td>{x.Role?.name!=='ADMIN'&&<div className="table-actions"><button className="btn btn-sm btn-outline-primary" onClick={()=>userAction(x,'role',x.Role?.name==='STUDENT'?'LECTURER':'STUDENT')}>Đổi vai trò</button><button className="btn btn-sm btn-outline-danger" onClick={()=>userAction(x,'status',x.status==='ACTIVE'?'LOCKED':'ACTIVE')}>{x.status==='ACTIVE'?'Khóa':'Mở khóa'}</button></div>}</td></tr>)}</tbody></table></div></section>
  <div className="catalog-grid"><Catalog title="Môn học" kind="subject" items={subjects} onEdit={(item=null)=>setCatalogModal({kind:'subject',item,name:item?.name||''})} onDelete={deleteCatalog}/><Catalog title="Danh mục" kind="category" items={categories} onEdit={(item=null)=>setCatalogModal({kind:'category',item,name:item?.name||''})} onDelete={deleteCatalog}/></div>
  <section className="surface-card admin-section"><div className="section-title-row"><div><span className="eyebrow">Dấu vết hệ thống</span><h2>Hoạt động gần đây</h2></div></div><div className="activity-list">{activities.map(x=><div key={x.id}><span className="activity-dot"/><p><strong>{x.User?.fullName||'Hệ thống'}</strong><small>{x.action} · {x.details}</small></p><time>{new Date(x.createdAt).toLocaleString('vi-VN')}</time></div>)}</div></section>
  {rejectItem&&<Modal title="Từ chối học liệu" onClose={()=>setRejectItem(null)}><p>Nhập lý do từ chối <strong>{rejectItem.title}</strong>.</p><textarea className="form-control" rows="4" value={reason} onChange={e=>setReason(e.target.value)} autoFocus/><div className="modal-actions"><button className="btn btn-light" onClick={()=>setRejectItem(null)}>Hủy</button><button className="btn btn-danger" onClick={reject}>Xác nhận</button></div></Modal>}{catalogModal&&<Modal title={`${catalogModal.item?'Chỉnh sửa':'Thêm'} ${catalogModal.kind==='subject'?'môn học':'danh mục'}`} onClose={()=>setCatalogModal(null)}><input className="form-control" value={catalogModal.name} onChange={e=>setCatalogModal({...catalogModal,name:e.target.value})} autoFocus/><div className="modal-actions"><button className="btn btn-light" onClick={()=>setCatalogModal(null)}>Hủy</button><button className="btn btn-primary" onClick={saveCatalog}>Lưu</button></div></Modal>}</div>}
function Catalog({title,kind,items,onEdit,onDelete}){return <section className="surface-card admin-section"><div className="section-title-row"><h2>{title}</h2><button className="btn btn-sm btn-primary" onClick={()=>onEdit()}>+ Thêm</button></div><div className="catalog-list">{items.map(x=><div key={x.id}><span>{x.name}</span><div><button onClick={()=>onEdit(x)}>Sửa</button><button onClick={()=>onDelete(kind,x)}>Xóa</button></div></div>)}</div></section>}
function Modal({title,onClose,children}){return <div className="modal-backdrop-custom" onMouseDown={onClose}><div className="reject-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><Icon name="close"/></button><h2>{title}</h2>{children}</div></div>}
