import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext.jsx';
import Icon from '../components/Icon.jsx';
export default function Login() {
  const [form,setForm]=useState({email:'',password:''}),[error,setError]=useState(''),[showPassword,setShowPassword]=useState(false),[loading,setLoading]=useState(false),nav=useNavigate(),{login}=useAuth();
  const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{await login(form.email,form.password);nav('/')}catch(x){setError(x.message)}finally{setLoading(false)}};
  return <div className="auth-page"><div className="auth-visual"><div className="auth-glow auth-glow-one"/><div className="auth-glow auth-glow-two"/><div className="auth-visual-content"><div className="brand-lockup auth-brand"><span className="brand-mark"><Icon name="book"/></span><span>KhIm Hub</span></div><span className="eyebrow light">Nền tảng học liệu số</span><h1>Học tập sâu hơn.<br/>Chia sẻ dễ dàng hơn.</h1><p>Không gian tập trung giúp bạn khám phá tài nguyên chất lượng, kết nối tri thức và nâng cao hiệu quả học tập.</p><div className="auth-benefits"><span><Icon name="shield"/> Nội dung được kiểm duyệt</span><span><Icon name="search"/> Tìm kiếm nhanh chóng</span></div></div></div><div className="auth-form-wrap"><div className="auth-card"><div className="auth-heading"><span className="mobile-auth-brand">KhIm Hub</span><h2>Chào mừng trở lại</h2><p>Đăng nhập để tiếp tục hành trình học tập của bạn.</p></div>{error&&<div className="alert alert-danger auth-alert">{error}</div>}<form onSubmit={submit}><label className="form-label">Địa chỉ email</label><div className="input-shell"><span className="input-prefix">@</span><input className="form-control" type="email" placeholder="name@example.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required autoFocus/></div><label className="form-label mt-3">Mật khẩu</label><div className="input-shell"><span className="input-prefix">••</span><input className="form-control" type={showPassword?'text':'password'} placeholder="Nhập mật khẩu" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button className="password-toggle" type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Hiện hoặc ẩn mật khẩu"><Icon name="eye" size={19}/></button></div><div className="form-check my-3"><input className="form-check-input" type="checkbox" id="remember"/><label className="form-check-label" htmlFor="remember">Ghi nhớ đăng nhập</label></div><button className="btn btn-primary btn-lg w-100 auth-submit" disabled={loading}>{loading?<><span className="spinner-border spinner-border-sm"/> Đang đăng nhập...</>:<>Đăng nhập <Icon name="arrow" size={18}/></>}</button></form><p className="switch-auth">Chưa có tài khoản? <Link to="/register">Đăng ký ngay</Link></p><p className="auth-note"><Icon name="shield" size={16}/> Phiên đăng nhập được bảo vệ an toàn</p></div></div></div>;
}
